### PR TITLE
Replaced Polyglot instance creation on componentWillReceiveProps

### PR DESCRIPTION
**Pull request by matheusmoreira-hotmart**
Replaced Polyglot instance creation on componentWillReceiveProps by locale and replace method calls.

Issue #8

### CODE REVIEW

**Comment by nayaabkhan** [comment]
@MattEliasHot LGTM, can you bump the version in `package.json` as well in the same commit?

**Comment by matheusmoreira-hotmart** [comment]
@nayaabkhan Done!

**Comment by chemitaxis** [comment]
Can you please merge and publish a new version? Thanks!

**Comment by nayaabkhan** [comment]
@MattEliasHot Thanks, code is okay now. Though I see a few things to fix in commits:

1. I see you have used a commit convention different than we like to use in the project. Can you update it?

    We use imperative style: `Replace Polyglot instance creation on componentWillReceiveProps by locale and replace method calls`

    Even better would be to clearly specify "what" is fixed instead of how: ```Prevent creation of multiple `Polyglot` instances on receiving new props```

2. Squash the commits so we have only one commit.
3. Also change version to `0.2.5`, I just pushed another patch at `0.2.4`.

**Comment by jacobpenny** [comment]
I'd love to use this lib but am waiting for this fix. I would be happy to make those changes but don't want to step on @MattEliasHot 's toes. Let me know if I can be of help.

**Comment by matheusmoreira-hotmart** [comment]
Done. @nayaabkhan, you should create a commit convention guide for this repo, maybe putting your comment above on the wiki section, and linking it to the README would already solve this issue. 

Also, while merging PR, Github provides you with the option to squash them into a single commit.
https://github.com/blog/2141-squash-your-commits

@jacobpenny If you have some urgency on this issue, feel free to use my fork. After this PR gets merged, you can simply switch the URL on package.json, and use this lib again.
https://stackoverflow.com/questions/23210437/npm-install-private-github-repositories-by-dependency-in-package-json

**Comment by nayaabkhan** [comment]
@MattEliasHot Thanks a lot, all good and published.

Yep, I want to spend some time to add tests and a contributing guide to the repo. Should be up soon 😉 

About the squash, I know about it but I prefer local squashing. It seems the squash from Github doesn't add any merge commit to history. But it is not a big deal anyways.

@jacobpenny @chemitaxis Enjoy the new release and let me know if anything. Cheers!

**Pull request merged**
